### ISSUE TITLE
Object type error

### ISSUE THREAD

**Issue by jl5000** [r-lib/httr2#118]
I'm trying the `req_oauth_password` flow (sorry no reprex) and I'm getting an error in `as.numeric(.date) + expires_in` within the `oauth_token()` function. I've debugged it and it seems like the `expires_in` variable is a string and also needs to be converted to a numeric.

**Comment by hadley** [comment]
Do you want to try doing a PR to fix it? I'm unlikely to have the time to work on httr2 myself in the near future, but I can find the time to review PRs.

**Comment by hadley** [comment]
It seems like this might be a problem with the specific API your using because `oauth_token()` is called from `oauth_client_get_token()` using the results from `oauth_flow_fetch()`, which should be in JSON, i.e. `expires_in` should be numeric.  

So this probably falls under this comment: https://github.com/r-lib/httr2/blob/main/R/oauth-flow.R#L5-L8

**Comment by jl5000** [comment]
I don't know if this is relevant but I was looking at the OAuth 2.0 documentation, and it suggests the expires_in parameter would always be a string (although I may be wrong): https://docs.spring.io/spring-security/oauth/apidocs/org/springframework/security/oauth2/common/OAuth2AccessToken.html

In any case, I had no idea how to go about making the changes you suggested, but with your comment above, I think I understand what I need to do.
