### ISSUE TITLE
Retrying (incl rate limits)

### ISSUE THREAD

**Issue by jennybc** [r-lib/httr2#13]
If nothing else, this blog post capture lots of important ergonomic considerations:

https://tech.channable.com/posts/2020-02-05-opnieuw.html

**Comment by hadley** [comment]
See also https://github.com/r-lib/gargle/blob/retry/R/request_retry.R and https://github.com/ropensci/rtweet/blob/master/R/http.R#L207-L225

**Comment by hadley** [comment]
Nice thing about OpNieuw is that the retries have two simple parameters: total number of times to try making the request and maximum amount of time to wait before last request. These are then used to determine the exponential multiplier: https://github.com/channable/opnieuw/blob/master/opnieuw/retries.py#L40-L73. However, I'm not convinced this is the most user friendly parameterisation, since if you're willing to wait longer you'd need to set both parameters.

**Comment by hadley** [comment]
Also need to think about rate-limiting retries. Would need some callback that's passed headers.

**Comment by hadley** [comment]
Types of retries:

* The internet is flaky (errors at curl/transport layer)
* The server is flaky (random 500 errors)
* The server is rate-limiting me (probably needs to be a separate function)

**Comment by hadley** [comment]
```R
req_policy_retry <- function(req, max_tries, max_time) {}
req_policy_rate_limit <- function(req, callback) {}
```

**Comment by hadley** [comment]
By default, should retry on 500s and curl errors, but should also provide the ability to specify a callback function so you can implement your own criteria (e.g. https://github.com/googleapis/nodejs-common/blob/56764dc58634d151f27b67869d38a7ef97708b6c/src/util.ts#L505-L536).

**Comment by hadley** [comment]
Now implemented in `req_retry()`.
