### ISSUE TITLE
Support for OAuth 2.0 device code flow

### ISSUE THREAD

**Issue by hongooi73** [r-lib/httr2#2]
Quick question, does httr support this natively? The idea is that you contact the endpoint. Then it sends back a link, which you open in your browser and enter a code which you get from a device. Once that's done, your app gets the token.

The IETF draft is here: https://tools.ietf.org/html/draft-ietf-oauth-device-flow-07

And an outline of how it works for Azure AD is here: https://joonasw.net/view/device-code-flow

**Comment by Hong-Revo** [comment]
I have some code here for using a device with Azure. Feel free to study/critique/steal.

https://github.com/cloudyr/AzureRMR/blob/master/R/AzureToken.R

**Comment by ijlyttle** [comment]
Same here, please feel free to use whatever might be useful:

https://github.com/ijlyttle/AzureOAuth

**Comment by Hong-Revo** [comment]
That AzureRMR link has migrated to a new repo:

https://github.com/cloudyr/AzureAuth

This implements OAuth2.0 tokens for Azure Active Directory v1 and v2, with some new functionality:

- Cache is located in a special data dir via rappdirs package, rather than in the working directory
- Add device_code and resource_owner grant methods
- Simplified UI, just specify resource/tenant/app/credentials in the one function

Again, feel free to study/critique/steal.
