### ISSUE TITLE
`httr2` gives "! Failed reading the chunked-encoded stream"

### ISSUE THREAD

**Issue by xinzhuohkust** [r-lib/httr2#261]
```
"https://www.zjzwfw.gov.cn/zjservice/matter/punishment/searchpunishlist.do" $
+             request() %>%
+             req_headers(
+                 "User-Agent" = "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Bui$
+                 "Accept-Encoding" = "gzip, deflate, br",
+                 "Accept" = "*/*",
+                 "Connection" = "keep-alive"
+             ) %>% 
+             req_body_form(
+                 "enddate" = "2022-12-17",
+                 "type" = "1",
+                 "pageNo" = "1",
+                 "bxzcf_type" = "0"
+             ) %>% 
+             req_timeout(30) %>% 
+             req_perform()
Error:
! Failed reading the chunked-encoded stream
Run `rlang::last_trace()` to see where the error occurred.
```

**Comment by hadley** [comment]
Can you please provide a minimal reprex (*repr*oducible *ex*ample)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please help me help you! If you've never heard of a reprex before, start by reading [about the reprex package](https://reprex.tidyverse.org/index.html), including the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by hadley** [comment]
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.
