### ISSUE TITLE
Return mocked responses

### ISSUE THREAD

**Issue by sckott** [r-lib/httr2#30]
With `httr` we can hook into requests via `set_callback`, which I use to make `webmockr` and `vcr` work. Can there be something similar here? 

cc @maelle

**Comment by hadley** [comment]
What exactly do you need to do with it?

**Comment by sckott** [comment]
We currently use `httr::set_callback` here in `webmockr`  https://github.com/ropensci/webmockr/blob/master/R/adapter-httr.R#L106-L117 to use our own code to process an HTTP request rather than it going through httr's internals. Does that make sense? We don't need anything specific for our needs, just the same ability `httr::set_callback` provides here in httr2

**Comment by hadley** [comment]
I'd prefer not to re-introduce something so general, but try for something more narrowly scoped.  Since requests are now explicit objects, maybe `req_fetch()` could become a generic, and then for mocking you'd start with a `mock_request()` instead of a `request()`?  Can you point me to something general about the goals of vcr/webmockr so I can remind myself exactly what they do?

**Comment by sckott** [comment]
I can't find anything that already exists, so here's a summary of each:

webmockr: The goal is to mock HTTP requests without actually performing any HTTP requests. With the package you create "stubs" that should match an HTTP request, with the specified return response body/headers/etc. Any HTTP request matching the stub will return the specified response body/headers/etc. 
vcr: The goal is to cache real HTTP request/response objects so that subsequent requests matching any cached requests are not actually performed but instead use the cached data. AFAIK vcr is similar in its goals to httptest.  

Where we hook into httr is in webmockr, and vcr uses webmockr, so the actual hook is only in webmockr.

Does that help at all?

**Comment by hadley** [comment]
Hmmmm, maybe we can handle this in a similar way to verbosity — https://httr2.r-lib.org/reference/req_perform.html. Something like this?

```R
req_perform <- function(req, path = NULL,
                        verbosity = getOption("httr2_verbosity", 0L),
                        mock = getOption("httr2_mock", NULL)) {
  check_request(req)

  if (!is.null(mock)) {
    mock_resp <- mock(req)
    if (is.null(mock_resp)) {
      return(mock_resp)
    }
  }
  ...
}
```

(Coupled with `with_mock()`/`local_mock()`)

I think this needs to be done via global option because you want the ability to mock some request deep within the stack, not just top-level requests (which is why my previous suggestion for `mock_request()` plus a generic `req_perform()` wouldn't help). 

cc @enpiar in case he has any thoughts

**Comment by maelle** [comment]
It's @nealrichardson :slightly_smiling_face:

**Comment by nealrichardson** [comment]
{httptest} works a bit differently: it monkey-patches `httr:::request_perform()` using `trace()` 🙈. For better or worse, I never got around to adapting it to use the `set_callback` approach. Agree that it needs to be global, and @hadley's proposal seems fine to me, though it doesn't (to my uninitiated eyes) look all that different from the `set_callback` way.

**Comment by hadley** [comment]
Yeah, it ended up pretty similar to `set_callback()`; it's now just more clear what the explicit purpose is.

**Comment by sckott** [comment]
I like your proposal @hadley Yes, agree, we need to be able to mock requests wherever they are in the stack.
