### ISSUE TITLE
Move token (a) caching and (b) refresh token layer from `req_oauth_*()` to `oauth_flow*()`

### ISSUE THREAD

**Issue by fh-mthomson** [r-lib/httr2#328]
**Goal**: use `oauth_flow_auth_code()` as a single function through which I can:

1. **Generate**: Create a token
2. **Cache**: Initialize/leverage a cache using ^ token (via `cache_choose()` et al)
3. **Refresh**: If a given token (new or cached) is expired, use the refresh token to generate a new token (rather than `oauth_flow_refresh()`, as discussed at length in #186)

Currently, only (1) is supported by `oauth_flow_auth_code()` whereas (2) & (3) are automated via [auth_outh_sign()](https://github.com/r-lib/httr2/blob/f9e73a3036f00dc96e499f9377b1e3a134b5ff8c/R/oauth.R#L31C1-L55) but only as an indirect side effect of calling `req_oauth_auth_code()`. 

**Proposal**: move the `auth_outh_sign()` logic to the token-generation layer, instead of (or in addition to) the request layer, since, e.g., `req_oauth_auth_code()` calls `oauth_flow_auth_code()` anyway.

**Comment by hadley** [comment]
Can you give a bit more context about why you want this? i.e. how does the current auth caching flow fail for you?

It's not really possible to move the caching code into `oauth_flow_auth_code()` because `req_perform()` handles the cache updating logic (via `auth_oauth_sign()`) when the token requires a refresh.

**Comment by hadley** [comment]
Are you sure you can't do this already by using `req_oauth_whatever()` with the the okta client but applied to the snowflake request?

**Comment by fh-mthomson** [comment]
Yeah, the token from Okta is passed through to initialize a Snowflake ODBC connection, via:
```
conn <- DBI::dbConnect(
  odbc::odbc(),
  .connection_string = snowflake_connection_string
)
```

Where `snowflake_connection_string` contains `AUTHENTICATOR=OAUTH;TOKEN=<X>`. Then, `conn` is used for all `tbl()` workflows using `dbplyr` translations.

**Comment by hadley** [comment]
Ah got it. I'll have to think about this use case more.

**Comment by hadley** [comment]
With okta, I assume that when you refresh the token, you get a new refresh token and a new access token?

Is the branching really on `is.null(token$refresh_token)` or is it more `is.null(token)`? (i.e. the token wasn't cached yet not that you got a token that can't be refreshed)

It seems like what you need is a public version of https://github.com/r-lib/httr2/blob/87e040dcff43efdfd157f05299101c795f572c1a/R/oauth.R#L40-L54. I think I could probably give you something like that fairly easily — it'll be a bit awkward (i.e. designed to be wrapped in another function) but at this point I'd prefer to not to commit adding another family of functions like `oauth_token_auth_code()`. (And I don't want to add caching to `oauth_flow_auth_code()` and friends, because there will still need to be a simple function that just implements each flow)

**Comment by fh-mthomson** [comment]
> With okta, I assume that when you refresh the token, you get a new refresh token and a new access token?

Correct, each of the following return distinct values for `access_token`, `expires_at`, and `refresh_token`:
- `httr2::oauth_flow_auth_code()`
- `httr2:::token_refresh()`

> Is the branching really on is.null(token$refresh_token) or is it more is.null(token)? (i.e. the token wasn't cached yet not that you got a token that can't be refreshed)

Is `refresh_token` always returned for all clients? Or, is it possible that some clients may only return  `access_token`? I'm leaning towards the current implementation: branching on `token$refresh_token` since that's the object that's immediately required in `token_refresh()`.

> It seems like what you need is a public version of this:

100%. thanks for the PR!

**Comment by jennybc** [comment]
If I am off-base, just ignore me, but this discussion gave me a vague memory of recording some related facts around what Google does:

https://github.com/r-lib/httr2/pull/168#discussion_r970213124
