### ISSUE TITLE
Check Azure certificate based auth

### ISSUE THREAD

**Issue by hadley** [r-lib/httr2#33]
https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#redeem-a-code-for-an-access-token

Something like this:

```R
client_id <- "my_client_id"
claims <- list(
  aud = "https://login.microsoftonline.com/{tenant}/v2.0",
  iss = client_id,
  sub = client_id
)
oauth_app(
  oauth_client("id"),
  endpoints = c(
    token = "https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token"
  ),
  auth = "jwt_enc",
  auth_params = list(
    claims = claims,
    key = "path/to/private/key",
    header = list(
      x5t = base64url_encode(openssl::sha1(openssl::read_cert("path/to/certificate")))
    )
  )
)
```

Login at <https://portal.azure.com/>. Need to figure out how to create app, and how to create certificate.

Create apps at https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade

See code in https://github.com/Azure/AzureAuth/blob/6f6ecf4ea47e3da35afe1e05e5c5a196a00b8aae/R/cert_creds.R

**Comment by hongooi73** [comment]
Sure, I can have a look at this. Although if all goes well, httr2 may well make AzureAuth obsolete, since its only purpose is to obtain OAuth tokens. That would be fine with me, since most of the tech support questions I get are about authentication 😅

**Comment by hadley** [comment]
I think there will still be some need for AzureAuth because there's some Azure specific stuff on top of the regular auth, but hopefully it can be much much smaller.

**Comment by hongooi73** [comment]
Some questions on the scope:

- Is the intention to support only AAD v2.0? I would assume so, since v1.0 is a kind of weird semi-compatible implementation of the RFC spec
- Do other providers also support certs? I only have access to Azure at the moment.

**Comment by hadley** [comment]
* Yes
* I haven't seen any others yet, although I assume they must exist

**Comment by hongooi73** [comment]
I've verified that the client credentials flow works with a certificate. Code:

```r
cert_client_id <- "guid"
cert_pem_file <- "path/to/pemfile-including-private-key"

cert_pem <- openssl::read_pem(cert_pem_file)
cert_key <- openssl::read_key(cert_pem[["PRIVATE KEY"]])
cert_cert <- openssl::read_cert(cert_pem[["CERTIFICATE"]])

cert_claims <- jose::jwt_claim(
    aud="https://login.microsoftonline.com/aicatr.onmicrosoft.com/v2.0",
    iss=cert_client_id,
    sub=cert_client_id,
    iat=as.numeric(Sys.time()),
    exp=as.numeric(Sys.time() + 3600)
)

x5t <- jose::base64url_encode(openssl::sha1(cert_cert))

cert_assert <- jose::jwt_encode_sig(
    claim=cert_claims,
    key=cert_key,
    size=256,
    header=list(x5t=x5t, kid=x5t)
)

scope <- "https://management.azure.com/.default"  # Azure Resource Manager

cert_app <- oauth_app(
    oauth_client(cert_client_id, client_secret=""),
    endpoints = c(
        token = "https://login.microsoftonline.com/aicatr.onmicrosoft.com/oauth2/v2.0/token"
    )
)

token <- oauth_flow_client_credentials(cert_app,
    scope=scope,
    token_params=list(
        client_assertion_type="urn:ietf:params:oauth:client-assertion-type:jwt-bearer",
        client_assertion=cert_assert
    )
)
```

One wart is that `oauth_flow_client_credentials` complains if there is no client secret, although this isn't needed if a cert is present. It should probably check for either a secret, or an assertion type plus assertion.

I'll look at the auth code flow in the next few days.

**Comment by hongooi73** [comment]
I'm unable to get the client creds flow working with the arguments to `oauth_app`. Does it expect the key to be in a specific format?

```r
cert_app2 <- oauth_app(
    oauth_client(cert_client_id, client_secret=""),
    endpoints = c(
        token = "https://login.microsoftonline.com/aicatr.onmicrosoft.com/oauth2/v2.0/token"
    ),
    auth="jwt_sig",
    auth_params=list(
        key=cert_key,
        claims=cert_claims,
        header=list(x5t=x5t, kid=x5t)
    )
)

oauth_flow_client_credentials(cert_app2, scope=myscope)
```
```
Error in !claims : invalid argument type
```

**Comment by hongooi73** [comment]
Also, when `oauth_flow_client_credentials` calls `oauth_flow_check_app`, it doesn't set `interactive=FALSE`, although this flow is specifically intended for non-interactive use.

**Comment by hadley** [comment]
Yeah, I think the idea of either a secret or a certificate to client is solid. I'll implement that and look into the other problems next week. Thanks for trying it out!

**Comment by hadley** [comment]
Once #46 is merged, you should be able to simplify to :

```R
cert_client_id <- "guid"

cert_pem <- openssl::read_pem("path/to/pemfile-including-private-key")
cert_key <- openssl::read_key(cert_pem[["PRIVATE KEY"]])
cert_cert <- openssl::read_cert(cert_pem[["CERTIFICATE"]])
x5t <- jose::base64url_encode(openssl::sha1(cert_cert))

cert_claims <- jose::jwt_claim(
  aud = "https://login.microsoftonline.com/aicatr.onmicrosoft.com/v2.0",
  iss = cert_client_id,
  sub = cert_client_id,
)

client <- oauth_client(
  id = cert_client_id,
  key = cert_key,
  token_url = "https://login.microsoftonline.com/aicatr.onmicrosoft.com/oauth2/v2.0/token",
  auth_params = list(
    headers = list(
      kid = x5t,
      x5t = x5t
    )
  )
)

token <- oauth_flow_jwt(
  client = client,
  claims = claims,
  scope = "https://management.azure.com/.default"
)
```

Is there a reason you used `oauth_flow_client_credentials()` instead of `oauth_flow_jwt`?

I'm reasonably sure the `!claims` bug is fixed — the key is (eventually) passed to `openssl::read_key()`, so should work with the formats you'd expect.

**Comment by hongooi73** [comment]
Because I wasn't aware of `oauth_flow_jwt` 🙂

I think of the flows as, well, _flows_: procedures that you follow to authenticate with the server. There are a number of them: authentication code, device code, client credentials, resource owner, implicit grant, etc. You can see a list of those supported by AAD [here](https://docs.microsoft.com/en-au/azure/active-directory/develop/v2-oauth2-auth-code-flow), in the sitemap on the left. I haven't used AWS or Google, but I assume things are similar there.

However, JWT isn't a flow, it's a data format. As such, I'm not sure that having a function called "oauth_flow_jwt" makes sense conceptually.

It looks like you're merging the app and client objects? That does makes sense to me; as far as I can tell, an "app" is basically provider terminology for what the RFC calls the "client". I do something similar in AzureAuth, albeit in a messier way.

**Comment by hadley** [comment]
Ooops, sorry, `oath_flow_jwt()` was a red-herring — there is a JWT flow, but azure doesn't use it (google does, for service account). So I think the example should be more like:

```R
cert_client_id <- "guid"

cert_pem <- openssl::read_pem("path/to/pemfile-including-private-key")
cert_key <- openssl::read_key(cert_pem[["PRIVATE KEY"]])
cert_cert <- openssl::read_cert(cert_pem[["CERTIFICATE"]])
x5t <- jose::base64url_encode(openssl::sha1(cert_cert))

cert_claims <- jose::jwt_claim(
  aud = "https://login.microsoftonline.com/aicatr.onmicrosoft.com/v2.0",
  iss = cert_client_id,
  sub = cert_client_id,
)

client <- oauth_client(
  id = cert_client_id,
  key = cert_key,
  token_url = "https://login.microsoftonline.com/aicatr.onmicrosoft.com/oauth2/v2.0/token",
  auth_params = list(
    claims = cert_claims,
    headers = list(
      kid = x5t,
      x5t = x5t
    )
  )
)

token <- oauth_flow_client_credentials(
  client = client,
  scope = "https://management.azure.com/.default"
)

**Comment by hadley** [comment]
(The two uses of JWT for OAuth are described in https://datatracker.ietf.org/doc/html/rfc7523 — I was confused for a while as to why google and Azure seem to use JWT in such totally different ways)

**Comment by hongooi73** [comment]
I may be wrong, but that RFC seems to be describing what Azure does when you use a certificate?

**Comment by hadley** [comment]
The flow (grant) is section 2.1; IIRC correctly what azure does is section 2.2.

**Comment by hongooi73** [comment]
See my edit; in Azure, certs can be used in both the client creds and auth code flow.

Section 2.1 is the client creds flow, and is basically what I tested above. Section 2.2 is auth code, which I haven't got to yet.

**Comment by hadley** [comment]
I bit the bullet and created and uploaded a certificate myself to verify that it all works. All the complicated stuff did but I'd messed up a couple of minor checks 🙄 — should be good now!

**Comment by hongooi73** [comment]
Great! I'd meant to check over the weekend that the auth code flow worked with a cert, but got distracted; I'll try to do that in the next few days.

**Comment by gwd666** [comment]
> ```r
> aicatr.onmicrosoft.com
> ```

@hongooi73 - could you pls enlighten me about the aicatr in "aicatr.onmicrosoft.com"? would really appreciate it - is that some dummy tenant or something completely different? also because you mentioned your Microsoft365R app being registered there?

**Comment by hongooi73** [comment]
In Azure, the OAuth endpoints are of the form

```
https://login.microsoftonline.com/{tenant}/oauth2/...
```

Where `tenant` can be one of

- A GUID
- A tenant name, which must be specified as `tenantname.onmicrosoft.com` (note it's "onmicrosoft", not "microsoft")
- A registered domain name, of the form `tenantdomain.com`
- A "wildcard" spec: `consumers`, `organizations` or `common`. `consumers` is for personal accounts only; `organizations` is for organizational (work & school) accounts and logs you into your default tenant; and `common` is for both. Things get complicated when you have a personal account that is also a guest account in an org; avoid using `common` in that case.

You can see your tenant GUID and name by logging in to the Azure portal and going to the AAD section. Normally people outside your org will never need to know your tenant details; while it's generally not recommended to tell people your tenant name, I don't think the actual security risk involved is significant.

"aicatr" is my own tenant, which I use for AzureR-related resources. Note that when you use Microsoft365R, or any of my other Azure packages, you supply **your own** tenant when logging in, not aicatr.

**Comment by gwd666** [comment]
> "aicatr" is my own tenant, which I use for AzureR-related resources. Note that when you use Microsoft365R, or any of my other Azure packages, you supply **your own** tenant when logging in, not aicatr.

That is where I am stuck with understanding your code - I just cannot find or figure out where you do the magic of moving from your tenant and app_id to eg my credentials? Since I guess when I use your package I am not being redirected to your aicatr tenant, right?

**Comment by hongooi73** [comment]
Don't worry about the aicatr tenant. It's irrelevant when you authenticate. The work is done by `AzureAuth::get_azure_token`, which takes as an input **your* tenant.

The app ID, which you also shouldn't need to worry about, is included as part of Microsoft365R. When you run `get_personal_onedrive`, it calls `get_azure_token` and passes it a fixed value for the ID. You can see this value in `Microsoft365R:::.microsoft365r_app_id`.

> Or is this registered app (and its ID) just a means of having an abstract registrar which in return just acts as a "provider" of those delegated permissions in the tenant (like Mail.Send., etc) - so the tenant doesn't really know a lot about the R package and what its functionality is it just provides abstract info on any Azure service or permission? Something along these lines?

Correct. Think of an app as just a bunch of code that sits on your machine, or your phone, or a server somewhere. As far as Azure is concerned, it doesn't need to know any specifics about this code. All it needs to know is that the app exists, and what it's allowed to do -- this is what the **app registration** is about. To Azure, when you authenticate and supply an app ID, it assumes that you are using that particular app, and therefore it lets you do whatever that app registration is set to allow.

> So essentially any package or app that knows that id and that list of delegated permissions could "re-use" that registration and contain code to utilize those functions like eg "Mail.Send", 

Yes. You could, if you wanted, run `get_azure_token`, pass it the value of `Microsoft365R:::.microsoft365r_app_id`, and get a token that way. From Azure's point of view, you *are* using Microsoft365R: this will show up in logs etc. But this isn't very interesting, because you're still limited by your own account permissions and whatever permissions Microsoft365R has in your tenant, so you can't actually do any malicious stuff.

> or am I missing some form of eg "secret" key in there?

There are different kinds of app registrations in Azure. A so-called "native client" is like what you describe: as long as you have the app ID, you can authenticate. There is also a "web app" registration type, which is meant for single-page apps running on a remote server. For these, authenticating also requires sending a client secret, which you generally won't have access to. Eg if the website running at `https://funkyapp.com` communicates with Azure, I can see their client ID, but I can't see their client secret -- which means I can't authenticate and pretend to be `funkyapp.com`.

PS @hadley on that note, in the httr docs I noticed before that you describe client secrets as sort-of-but-not-quite passwords: while you shouldn't make them public, there's little danger in doing so. I think the language should be stronger than that: they *are* passwords, and they perform a security role. It's just that in most R use cases, the client is also the server, and hence the user already has full access.

**Comment by hadley** [comment]
Yeah, although I now think the reason that the client secret isn’t that important is that for most services the client can’t actually do anything in its own right - the exception tend to be the big services like azure etc. Regardless, the docs around this should be considerably better in httr2 and I also provide some lightweight tools to obfuscate the secret to prevent it from being scraped.
