### ISSUE TITLE
Tests fail if httr2 not installed in global env

### ISSUE THREAD

**Issue by fh-mthomson** [r-lib/httr2#412]
To reproduce:
1. Uninstall `httr2`
2. Run `devtools::test()`

4 tests fail in `test-iterate.R`, I suspect due to https://github.com/r-lib/httr2/blob/10f3d878da94f2597c02c29846d446f3fbd635c8/tests/testthat/test-iterate.R#L61

**Comment by hadley** [comment]
I think the root cause is more likely to be something to do with the test server in `example_url()`.

...

Ah yes, if you `remove.packages("httr2")` then do `browseURL(paste0(example_url(), "/iris"))` you'll see

```
Error in seq2(start, end): could not find function "seq2"
```

I suspect this works when httr2 is installed because of something to do with the way that the functions are serialized when they're shipped to the process that runs the app. I have a vague recollection that the namespace will be captured and restored if available. I'll a fix momentarily.
