### ISSUE TITLE
HTTP Versions

### ISSUE THREAD

**Issue by NateNohling** [r-lib/httr2#574]
I have a website that I have had a significant amount of httr2::req_perform code suddenly returning only 403 errors. I have changed user_agent and headers with no luck. 

Python code using http.client using the exact same settings in positron works fine, so I am wondering if its due to HTTP 1.1 vs HTTP 2 or HTTP 3. Is there anyway to update the get request to a different HTTP version? Currently wrote a workaround using rvest::read_html_live but would like to go back to httr2 if possible.

**Comment by hadley** [comment]
Can you please provide a minimal reprex (*repr*oducible *ex*ample)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please help me help you! If you've never heard of a reprex before, start by reading [about the reprex package](https://reprex.tidyverse.org/index.html), including the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.
