### ISSUE TITLE
Encrypt/decrypt of tokens

### ISSUE THREAD

**Issue by jennybc** [r-lib/httr2#6]
https://gargle.r-lib.org/articles/articles/managing-tokens-securely.html

**Comment by hadley** [comment]
I wonder if we should also provide something like `req_oauth2_token()` where you could provide a client (id + optional secret + auth mechansim), and refresh token. That would make it easy to set up automated tests or other unattended jobs.

Somewhat related, but we should provide a simple way of encrypting client secrets so that their plain text doesn't appear in the source of the package. This isn't hugely secure because the motivated attacker could just call the appropriate decryption function, but it protects against automation which is the more likely attack mode.
